apps/codebility/lib/validations/auth.ts

CODEB-23 Signup form validation

---

apps/codebility/app/(marketing)/_components/marketing_modals/marketing-faqs-modal.tsx

Codebility | CODEB-11: Styling FAQs

---

apps/codebility/app/(marketing)/_components/marketing_modals/marketing-terms-and-condition-modal.tsx

Codebility | CODEB-12: Styling Terms & Condition

---

apps/codebility/app/(marketing)/_components/marketing_modals/marketing-privacy-policy-modal.tsx

Codebility | CODEB-13: Styling Privacy Policy

---

apps/codebility/app/home/_components/home-left-sidebar.tsx
apps/codebility/app/home/_components/home-mobile-navbar.tsx

changes:
- hide sidebar in small screens
- display sidebar items on mobile sidebar
output:

Codebility | CODEB-22: Sidebar Styling Issue

---

apps/codebility/app/home/applicants/_components/applicants-action-buttons.tsx
apps/codebility/app/home/applicants/_components/applicants-table-desktop.tsx
apps/codebility/app/home/applicants/_components/applicants-table-mobile.tsx
apps/codebility/app/home/applicants/action.ts
apps/codebility/app/home/applicants/loading.tsx

changes:
- refactor accept and deny action
- fix styling for mobile and desktop view
old
new

Codebility | CODEB-19: Refactor Applicants

---

apps/codebility/app/(marketing)/profiles/[id]/page.tsx
apps/codebility/app/(marketing)/profiles/page.tsx
apps/codebility/app/home/in-house/_components/in-house-card.tsx
apps/codebility/app/home/in-house/_components/in-house-cards.tsx
apps/codebility/app/home/in-house/_components/in-house-edit-table-body.tsx
apps/codebility/app/home/in-house/_components/in-house-editable-card.tsx
apps/codebility/app/home/in-house/_components/in-house-select.tsx
apps/codebility/app/home/in-house/_components/in-house-table-body.tsx
apps/codebility/app/home/in-house/_components/in-house-table-header.tsx
apps/codebility/app/home/in-house/_components/in-house-table.tsx
apps/codebility/app/home/in-house/actions.ts
apps/codebility/app/home/in-house/page.tsx
apps/codebility/lib/server/codev.service.ts
apps/codebility/types/home/codev.ts

changes:
- add type column in inhouse
- refactor get codev service
- update styling (in small screen and large screens)
- set max width
desktop screen
desktop screen (edit)
small screen
small screen (edit)
medium screen
medium screen (edit)

Codebility | CODEB-33: In-House Add Column Type

---

apps/codebility/app/home/_components/home-left-sidebar.tsx
apps/codebility/app/home/_components/home-mobile-navbar.tsx
apps/codebility/app/home/settings/loading.tsx
apps/codebility/app/home/settings/permissions/_components/permissions-table-row-mobile.tsx
apps/codebility/app/home/settings/permissions/_components/permissions-table-row.tsx
apps/codebility/app/home/settings/permissions/_components/permissions-table.tsx
apps/codebility/app/home/settings/permissions/_types/permissions.ts
apps/codebility/app/home/settings/permissions/action.ts
apps/codebility/app/home/settings/permissions/loading.tsx
apps/codebility/app/home/settings/permissions/page.tsx
apps/codebility/app/home/settings/resume/_components/resume-skills.tsx
apps/codebility/app/home/settings/resume/loading.tsx
apps/codebility/app/home/settings/resume/page.tsx
apps/codebility/app/home/settings/roles/_components/role-container.tsx
apps/codebility/app/home/settings/roles/action.ts
apps/codebility/app/home/settings/roles/loading.tsx
apps/codebility/app/home/settings/roles/page.tsx
apps/codebility/app/home/settings/services/_components/service-table.tsx
apps/codebility/app/home/settings/services/_lib/constants.ts
apps/codebility/app/home/settings/services/loading.tsx
apps/codebility/app/home/settings/services/page.tsx
apps/codebility/middleware.ts

changes:
ui changes
- resume loading ui (desktop)
- resume loading ui (mobile)
- roles loading ui (desktop)
- roles loading ui (mobile)
- permissions loading ui (desktop)
- permissions loading ui (mobile)
- services loading ui (desktop)
- services loading ui (mobile)

Codebility | CODEB-36: Refactor Settings

---

apps/codebility/app/home/clients/_lib/schema.ts
apps/codebility/middleware.ts

Codebility | CODEB-37: Can't Access Clients Archive

---

apps/codebility/app/(marketing)/profiles/_components/profile-lists-filter.tsx

style: update SelectItem component with dark mode focus state

CODEBILITY | CODEB-16 Styling Codevs Filter

---

apps/codebility/Components/modals/ClientEditModal.tsx
apps/codebility/app/home/clients/_components/clients-card.tsx
apps/codebility/app/home/clients/action.ts
apps/codebility/app/home/clients/loading.tsx
apps/codebility/app/home/clients/service.ts

changes: 
- refactor actions for upload image, delete image, update client and delete client
- update the styling of loading ui
- refactor edit client modal
- refactor client card
- refactor client service, the get all clients from supabase
loading ui

Codebility | CODEB-39: Update client not working

---

apps/codebility/app/(marketing)/codevs/_components/codevs-carousel.tsx

Codebility | CODEB-43: Fix Codevs

---

apps/codebility/app/home/tasks/_components/tasks-container.tsx
apps/codebility/app/home/tasks/page.tsx

changes:
- set max width and position to center
- add simple placeholder if no assigned task

Codebility | CODEB-35: My tasks is not render properly

---

apps/codebility/Components/modals/ProjectAddModal.tsx
apps/codebility/Components/modals/ProjectDeleteModal.tsx
apps/codebility/Components/modals/ProjectEditModal.tsx
apps/codebility/Components/modals/ProjectMembersModal.tsx
apps/codebility/Components/modals/ProjectViewModal.tsx
apps/codebility/app/home/projects/_components/projects-card.tsx

changes:
- fix project modal error
- refactor project view modal

Codebility | CODEB-46: Cleanup Projects Page

---

apps/codebility/Components/modals/ProfileModal.tsx
apps/codebility/app/home/interns/_components/intern-card.tsx
apps/codebility/app/home/interns/_components/intern-container.tsx
apps/codebility/app/home/interns/_components/intern-list.tsx
apps/codebility/app/home/interns/page.tsx
apps/codebility/types/home/codev.ts

changes: 
- set interns data
- refactor interns page and intern card
- use codev type
ui changes:
- interns page (old)
- interns page (new)
- interns profile (old)
- interns profile (new)

Codebility | CODEB-45: Display Interns Data

---

apps/codebility/Components/modals/AvailableTimeModal.tsx
apps/codebility/Components/modals/TechStackModal.tsx
apps/codebility/app/authv2/actions.ts
apps/codebility/app/authv2/sign-in/_components/sign-in-form.tsx
apps/codebility/app/authv2/sign-in/page.tsx
apps/codebility/app/authv2/sign-up/_components/sign-up-form.tsx
apps/codebility/app/authv2/sign-up/_components/sign-up-input.tsx
apps/codebility/app/authv2/sign-up/page.tsx
apps/codebility/lib/validations/auth.ts

changes:
- fix error on modals
- update responsive styling of sign in and sign up page
- new fields in sign up: github and image profile input
- update schema
- update supabase trigger
- invalid credentials if user email exists

Codebility | CODEB-53: Already existing user Error handling 

---

apps/codebility/Components/modals/ApplicantsAddModal.tsx
apps/codebility/app/home/applicants/_components/applicants-table-desktop.tsx
apps/codebility/app/home/applicants/_components/applicants-table-mobile.tsx
apps/codebility/app/home/applicants/_lib/constants.ts
apps/codebility/app/home/applicants/_types/applicants.ts
apps/codebility/app/home/applicants/action.ts

changes:
- create table for declined applicants in supabase
- refactor reject action
- display applicants image (for mobile and desktop)
- fix error on modal
ui changes:
when hovering
small screen

Codebility | CODEB-55: Applicants Image

---

apps/codebility/app/(marketing)/declined/_components/declined-buttons.tsx
apps/codebility/app/(marketing)/declined/_types/index.ts
apps/codebility/app/(marketing)/declined/actions.ts
apps/codebility/app/(marketing)/declined/page.tsx
apps/codebility/middleware.ts

changes:
- refactor middleware
- create declined page
- reapply button after 3 months
ui
after 3 months

Codebility | CODEB-50: Declined Application Notification

---

apps/codebility/Components/modals/AddRoleModal.tsx
apps/codebility/Components/modals/ApplicantsAddModal.tsx
apps/codebility/Components/modals/ApplicantsEditModal.tsx
apps/codebility/Components/modals/AvailableTimeModal.tsx
apps/codebility/Components/modals/BoardAddModal.tsx
apps/codebility/Components/modals/ClientAddModal.tsx
apps/codebility/Components/modals/ClientEditModal.tsx
apps/codebility/Components/modals/DeleteRoleModal.tsx
apps/codebility/Components/modals/EditRoleModal.tsx
apps/codebility/Components/modals/ListAddModal.tsx
apps/codebility/Components/modals/ProfileModal.tsx
apps/codebility/Components/modals/ProjectAddModal.tsx
apps/codebility/Components/modals/ProjectDeleteModal.tsx
apps/codebility/Components/modals/ProjectEditModal.tsx
apps/codebility/Components/modals/ProjectMembersModal.tsx
apps/codebility/Components/modals/ProjectViewModal.tsx
apps/codebility/Components/modals/ServiceCategoriesDeleteModal.tsx
apps/codebility/Components/modals/ServiceCategoriesModal.tsx
apps/codebility/Components/modals/TaskAddModal.tsx
apps/codebility/Components/modals/TaskDeleteModal.tsx
apps/codebility/Components/modals/TaskEditModal.tsx
apps/codebility/Components/modals/TaskViewModal.tsx
apps/codebility/Components/modals/TechStackModal.tsx
apps/codebility/app/home/_components/home-mobile-navbar.tsx

Issues:
- double close
solutions:
- to fix the "Warning: Missing Description ... ", you need to add "aria-describedby={undefined}" in DialogContent
- to fix "form cannot be descendant of p", you need to remove DialogDescription and add "aria-describedby={undefined}" in DialogContent
note: the best way is to remove DialogDescription why? because if you put the DialogDescription inside form a new error will arise
- to fix the double close, you just need to remove the close button

Codebility | CODEB-56: Cleanup Modals

---

apps/codebility/app/home/layout.tsx
apps/codebility/lib/server/codev.service.ts

Codebility | CODEB-40 In-House Page Unhandled Runtime Error

---

apps/codebility/Components/modals/BoardAddModal.tsx
apps/codebility/Components/modals/ProjectAddModal.tsx
apps/codebility/Components/modals/ProjectEditModal.tsx
apps/codebility/Components/modals/ProjectMembersModal.tsx
apps/codebility/Components/modals/ProjectViewModal.tsx
apps/codebility/app/(marketing)/_components/marketing-navigation-main.tsx
apps/codebility/app/home/_hooks/supabase/use-fetch-enum.ts
apps/codebility/app/home/kanban/[id]/_hooks/use-fetch-members.ts

changes:
- fix multiple gotrue client warning
- fix project view modal warning
- fix marketing sidebar warning

Codebility | CODEB-60: Cleanup Console Warnings

---

apps/codebility/Components/modals/ProjectAddModal.tsx
apps/codebility/app/(marketing)/_components/marketing-navigation-main.tsx
apps/codebility/app/(marketing)/_components/marketing-navigation.tsx

User story
As a user, I would like the marketing header navigation to include the same profile dropdown, enabling easy access to settings and the homepage.
Acceptance criteria

Codebility | CODEB-26 Marketing Page - Feature: Profile Dropdown

---

apps/codebility/Components/modals/TaskAddModal.tsx
apps/codebility/Components/modals/TaskDeleteModal.tsx
apps/codebility/Components/modals/TaskEditModal.tsx
apps/codebility/Components/modals/TaskViewModal.tsx
apps/codebility/app/home/kanban/[id]/_components/kanban-task.tsx
apps/codebility/app/home/kanban/[id]/_components/kanban_modals/kanban-add-modal-members.tsx
apps/codebility/app/home/kanban/[id]/_hooks/use-fetch-members.ts
apps/codebility/app/home/kanban/[id]/actions.ts
apps/codebility/app/home/kanban/page.tsx
apps/codebility/app/home/projects/_types/projects.ts
apps/codebility/app/home/projects/actions.ts

Codebility | CODEB-61: Kanban Enhancement

---

apps/codebility/app/home/_components/home-left-sidebar.tsx
apps/codebility/app/home/_components/home-mobile-navbar.tsx
apps/codebility/app/home/_components/user-provider.tsx
apps/codebility/app/home/layout.tsx
apps/codebility/middleware.ts

changes:
- check application status, if not yet accepted return null on sidebar items for mobile and desktop screen
- declined applicants can now access account settings

Codebility | CODEB-62: Sidebar Items Permissions for not Accepted

---

apps/codebility/Components/shared/dashboard/RenderTeam.tsx
apps/codebility/app/home/time-tracker/_components/time-tracker-table-desktop.tsx
apps/codebility/app/home/time-tracker/_components/time-tracker-table-mobile.tsx
apps/codebility/app/home/time-tracker/_components/time-tracker-table.tsx
apps/codebility/app/home/time-tracker/loading.tsx
apps/codebility/app/home/time-tracker/page.tsx

changes: 
- loading ui
- fix time tracker table
- display simple placeholder text "No data" if empty
- format time to readable
ui changes:
- loading 
- table - format the time to readable
- table (old)

Codebility | CODEB-64: Refactor Time Tracker

---

apps/codebility/app/authv2/password-reset/_components/password-reset-form.tsx
apps/codebility/app/authv2/password-reset/page.tsx

changes: 
- fix forgot password page not found - retrieve forgot password ui from old code base

Codebility | CODEB-54: Forgot password page not found

---

apps/codebility/app/authv2/sign-in/_components/sign-in-form.tsx
apps/codebility/app/home/_components/home-toast-notification.tsx
apps/codebility/app/home/layout.tsx

As a user whose application has been accepted, I want to access my dashboard upon signing in, so that I can begin utilizing Codebility's services.
Acceptance Criteria:
- Given my application status is "Accepted"
- When I sign in to my account,
- Then I am redirected to my user dashboard.
- The dashboard displays a confirmation message:
- I have full access to all member features and functionalities.

Codebility | CODEB-49 : Accepted Application Routing

---

apps/codebility/app/(marketing)/declined/_components/declined-countdown.tsx
apps/codebility/app/(marketing)/declined/page.tsx

Codebility | CODEB-51: Access During 3-Month Reapplication Waiting Period

---

apps/codebility/app/(marketing)/thank-you/page.tsx
apps/codebility/app/authv2/sign-up/_components/sign-up-form.tsx
apps/codebility/middleware.ts

changes: 
- create thank you page
- redirect to thank you page after sign up
- add thank you page in middleware

Codebility | CODEB-47: Thank You Page After Sign-Up

---

apps/codebility/app/home/account-settings/_components/account-settings-change-password.tsx
apps/codebility/app/home/account-settings/_components/account-settings-header.tsx
apps/codebility/app/home/account-settings/action.ts
apps/codebility/app/home/account-settings/page.tsx

changes:
- display current logged in email
- ability to change password
- update account settings page

Codebility | CODEB-29: Change Password: The ability to update my current password to ensure security of my account.

---

apps/codebility/app/(marketing)/_components/marketing-navigation-main.tsx
apps/codebility/app/(marketing)/profiles/page.tsx
apps/codebility/app/(marketing)/profiles/style.css
apps/codebility/app/home/_components/home-navbar.tsx
apps/codebility/next.config.mjs

**apps/codebility/app/(marketing)/_components/marketing-navigation-main.tsx**
- added `modal={false}` to `<DropdownMenu>` to prevent scrollbar from hiding
- the seemingly plenty of changes on this file is only due to Prettier format on save.
**apps/codebility/app/(marketing)/profiles/page.tsx**
- cannot be solved by adding a `modal={false}` prop. (ShadCN's `<Select>` element causes this layout shift)
- added a separate CSS to override scrollbar settings
**apps/codebility/app/home/_components/home-navbar.tsx**
added `modal={false}` to `<DropdownMenu>` to prevent scrollbar from hiding

fix: prevent scrollbar from hiding when using dropdown menu

---

apps/codebility/app/(marketing)/_components/marketing-navigation-main.tsx
apps/codebility/app/(marketing)/_components/marketing-navigation-mobile-drawer.tsx

- added a new menu link to the dropdown menu
- ui fix: chevron icon based on open/close state of dropdown menu
- moved `<Sheet>` to a new file and named it `<MarketingNavigationMobileDrawer />`, then moved its trigger button to the left side of the navbar.

fix: added link to dashboard on the dropdown link at marketing page

---

apps/codebility/app/(marketing)/codevs/_components/codevs-hero.tsx

In supabase, having an undefined value for an id of type uuid would cause an 400 error. and that error is not being handled as shows in here:
```bash
const { data, error } = await supabase
.from("codev")
.select("application_status")
.eq("user_id", userId)
.single();
```
One possible solution is to check whether there is logged user or not before running the code above.

fix: check for undefined user id.

---

apps/codebility/app/home/layout.tsx

fix: Decrease margin-top at dashboard

---

apps/codebility/app/home/_components/home-left-sidebar.tsx

fix: Navbar links hover color margins

---

apps/codebility/.env.example
apps/codebility/config/app.config.ts

- signups now redirect to NEXT_PUBLIC_APP_BASE_URL instead of NEXT_PUBLIC_SITE_URL

fix: modified env references

---

apps/codebility/app/home/in-house/_components/cards/codev-card.tsx

Fix the rendered position data in codev-card.tsx.

Fix position data being displayed in the card ui

---

apps/codebility/app/globals.css
apps/codebility/app/home/in-house/_components/cards/codev-card.tsx

Create a temporary fix on code-dev card techstack images not rendering

Fix techstack image rendering

---

apps/codebility/app/home/projects/_components/ProjectEditModal.tsx
apps/codebility/app/home/settings/profile/_components/Photo.tsx
apps/codebility/app/home/settings/profile/_components/UploadPhotoModal.tsx

added:
-image cropper in profile
fixed:
-font color in edit project
-remove console logs in image cropper

feat: added image cropper in profile, fix font color in project

---

apps/codebility/app/(marketing)/services/_components/services-service-card.tsx
apps/codebility/app/home/projects/_components/projects-card.tsx

fix:
-fixed project icon not matching
-fixed project status not visually clear
-readjusted project image in service

fix: ui bug in project(icon color, project status), adjusted project image in service

---

apps/codebility/app/home/projects/_components/projects-card.tsx

[Screencast from 02-19-2025 05:30:21 PM.webm](https://github.com/user-attachments/assets/f791a961-f532-4a6a-a17d-309ac4a11927)

improvement: remove project card buttons, and make the card clickable

---

apps/codebility/Components/ui/SwitchStatusButton.tsx
apps/codebility/app/home/clients/_components/clients-card.tsx

https://github.com/user-attachments/assets/9b0fc1d3-01cf-4128-92d0-b9dfd3e13fd7

added: switch button on client page card

---

apps/codebility/lib/server/codev.service.ts

fix:codev-fetching-issue

---

apps/codebility/app/home/interns/_components/CodevCard.tsx
apps/codebility/app/home/interns/_components/CodevList.tsx
apps/codebility/lib/server/codev.service.ts

improvement:
updated codev card
fix:
included codev_points in codev query
https://github.com/user-attachments/assets/5b2617ab-fc43-4a66-aa72-effbfd4e1fa6

improvement: update ui of codev card, fix: codev_points query

---

apps/codebility/app/home/applicants/_components/ApplicantsActionButtons.tsx
apps/codebility/app/home/applicants/_components/ApplicantsTableDesktop.tsx
apps/codebility/app/home/applicants/_components/ApplicantsTableMobile.tsx

Rowell/fix  applicants remove edit button

---

apps/codebility/app/globals.css
apps/codebility/app/home/applicants/_components/ApplicantsActionButtons.tsx
apps/codebility/app/home/applicants/_components/ApplicantsTableDesktop.tsx
apps/codebility/app/home/applicants/_components/ApplicantsTableMobile.tsx

Before
After
Fix hovercard width size and opacity

Rowell/fix  applicants hovercard styling

---

apps/codebility/app/home/interns/_components/CodevCard.tsx
apps/codebility/app/home/interns/_components/CodevList.tsx
apps/codebility/app/home/interns/_components/TechStacks.tsx
packages/ui/src/checkbox.tsx

https://github.com/user-attachments/assets/e9204f1c-1d46-4f14-b24d-145815d67858

fix: codev card (uneven style), checkbox color

---

apps/codebility/Components/ui/dialog.tsx
apps/codebility/app/home/clients/_components/ClientAddModal(Old).tsx
apps/codebility/app/home/clients/_components/ClientAddModal.tsx
apps/codebility/app/home/clients/action.ts
packages/ui/src/select.tsx

Added countries and client type fields

Rowell/fix  clients refactor modal form

---

apps/codebility/app/home/(dashboard)/_components/DashboardProfile.tsx
apps/codebility/app/home/(dashboard)/actions.ts
apps/codebility/app/home/in-house/_components/table/EditableRow.tsx
apps/codebility/app/home/in-house/_components/table/InHouseTable.tsx
apps/codebility/app/home/in-house/_components/table/columns.ts

add:
added availability status switch in user dashboard and inhouse table
fix:
uneven editable row style in inhouse
https://github.com/user-attachments/assets/05b12e8b-289b-4f68-9d4d-237c77c4e781

feat: added availablity switch in userdashboard and inhouse

---

apps/codebility/app/home/clients/_components/ClientAddModal.tsx
apps/codebility/app/home/clients/_components/ClientEditModal.tsx
apps/codebility/app/home/clients/_components/ClientsCard.tsx
apps/codebility/app/home/clients/_lib/schema.ts
apps/codebility/app/home/clients/action.ts

Before
After
Did the following changes in ClientEditModal.tsx:
* Update the html structure
* Update the handleUpdateClient function to include country and client_type
Did the following changes in action.ts:
* Refactor the createClientAction to include country and client_type
* Refactor the updateClientAction to include country and client_type
Did the following changes in ClientAddModal.tsx:
* Refactor the handleCreateClient to include country and client_type

Rowell/fix  client edit modal form

---

apps/codebility/app/home/kanban/[id]/_components/tasks/TaskAddModal.tsx
apps/codebility/app/home/kanban/[id]/_components/tasks/TaskEditModal.tsx
apps/codebility/app/home/kanban/[id]/_components/tasks/TaskViewModal.tsx
apps/codebility/app/home/kanban/[id]/actions.ts

kanban update

---

apps/codebility/Components/CodevBadge.tsx
apps/codebility/app/(marketing)/profiles/_components/CodevListFilter.tsx

fix: hire codev page, codev badge tooltip and filter

---

apps/codebility/app/home/interns/_components/CodevList.tsx
apps/codebility/app/home/interns/_lib/codevpriority.ts
apps/codebility/constants/index.ts

changes:
codev list from 15 to 16
prioritization of codevs
**Before**
**After**

refactor: apply prioritization before filtering in CodevList

---

apps/codebility/app/home/kanban/[id]/_components/KanbanBoard.tsx
apps/codebility/app/home/kanban/[id]/_components/KanbanBoardColumnContainer.tsx
apps/codebility/app/home/kanban/[id]/_components/UserTaskFilter.tsx

kanban enhancements (filter by user)

---

apps/codebility/app/(marketing)/codevs/_components/CodevsCarousel.tsx
apps/codebility/app/(marketing)/codevs/page.tsx

changes:
codev page
-project carousel added 10sec autoplay delay when being interacted
-codev section move above the who we are

fix: codev project display autoplay, move codev section

---

apps/codebility/app/home/orgchart/_components/OrgChart.tsx
apps/codebility/app/home/orgchart/_components/OrgChartTeamMemberCard.tsx
apps/codebility/app/home/orgchart/_types/org-chart.ts
apps/codebility/app/home/orgchart/page.tsx

feat: redesigned of organizational chart

---

apps/codebility/Components/modals/PrivacyPolicyModal.tsx
apps/codebility/app/auth/sign-up/_components/SignUpForm.tsx

https://github.com/user-attachments/assets/95f7683f-0253-4642-92d3-cb3f1cebcbf0

fix: privacy modal in signup page

---

apps/codebility/app/home/kanban/[id]/_components/tasks/TaskAddModal.tsx

Capitalized the 1st letter of the chosen option for task, difficulty, and priority.

Fix capitalization of task type, difficulty, and priority

---

apps/codebility/app/home/(dashboard)/_components/DashboardTokenPoints.tsx

chore: Added skeleton on token points

---

apps/codebility/app/home/kanban/[id]/_components/tasks/TaskAddModal.tsx
apps/codebility/app/home/kanban/[id]/actions.ts

Primary assignee is no longer required and now has "optional" beside the label.

Change primary assignee from required to optional

---

apps/codebility/middleware.ts

fix: Book a call route directing to sign-in page

---

apps/codebility/app/home/(dashboard)/_components/DashboardCurrentProject.tsx
apps/codebility/app/home/(dashboard)/_components/DashboardProfile.tsx
apps/codebility/app/home/page.tsx

feat: Re-design of Current Projects

---

apps/codebility/app/home/(dashboard)/_components/DashboardCurrentProject.tsx

fix current projects skeleton having fixed width and exceeding on xl screen

improve dashboard skeleton

---

apps/codebility/app/home/projects/_components/ProjectCard.tsx

Fix: Project card team members

---

apps/codebility/Components/ui/SwitchStatusButton.tsx
apps/codebility/app/home/in-house/_components/table/InHouseTable.tsx
apps/codebility/app/home/kanban/page.tsx
apps/codebility/app/home/projects/_components/ProjectCard.tsx
apps/codebility/app/home/projects/actions.ts
apps/codebility/types/home/codev.ts

Fix: Added switch button on projects

---

apps/codebility/Components/ui/SwitchStatusButton.tsx
apps/codebility/app/home/in-house/_components/table/InHouseTable.tsx
apps/codebility/app/home/kanban/page.tsx
apps/codebility/app/home/projects/_components/ProjectCard.tsx
apps/codebility/app/home/projects/actions.ts
apps/codebility/types/home/codev.ts

Fix: Change active_switch column

---

apps/codebility/app/auth/sign-in/_components/SignInInput.tsx

fix: change password show password eyeIcon color

---

apps/codebility/app/auth/actions.ts
apps/codebility/app/auth/declined/_components/DeclineComponent.tsx
apps/codebility/app/auth/declined/_components/DeclinedButtons.tsx
apps/codebility/app/auth/declined/_components/DeclinedCountdown.tsx
apps/codebility/app/auth/declined/_service/actions.ts
apps/codebility/app/auth/declined/_service/util.ts
apps/codebility/app/auth/declined/page.tsx
apps/codebility/types/home/codev.ts

update:
made auth/decline page server comp
added Reapply button
added new column in codev date_applied

feat: updated auth/decline

---

apps/codebility/app/home/_components/MobileNav.tsx

fix admin dashboard icon mobile size

---

apps/codebility/app/home/_components/Navbar.tsx
apps/codebility/app/home/page.tsx
apps/codebility/constants/sidebar.ts

refactor: Change Settings Icon, Change Dashboard to Home

---

apps/codebility/app/home/projects/_components/ProjectFilterButton.tsx
apps/codebility/app/home/projects/page.tsx

feat: Added Project Filters

---

apps/codebility/app/home/(dashboard)/_components/DashboardCurrentProject.tsx
apps/codebility/app/home/(dashboard)/_components/DashboardCurrentProjectButton.tsx
apps/codebility/app/home/(dashboard)/_components/DashboardCurrentProjectModal.tsx

refactor: Current Projects design

---

apps/codebility/app/(marketing)/_components/MarketingNavigation.tsx
apps/codebility/app/applicant/layout.tsx
apps/codebility/app/applicant/waiting/_component/Stepper.tsx
apps/codebility/app/applicant/waiting/_component/applicantStep1.tsx
apps/codebility/app/applicant/waiting/_component/applicantStep2.tsx
apps/codebility/app/applicant/waiting/_component/applicantStep3.tsx
apps/codebility/app/applicant/waiting/_component/applicationSteps.tsx
apps/codebility/app/applicant/waiting/_component/testCountDown.tsx
apps/codebility/app/applicant/waiting/_component/testInstruction.tsx
apps/codebility/app/applicant/waiting/_service/action.ts
apps/codebility/app/applicant/waiting/_service/type.ts
apps/codebility/app/applicant/waiting/_service/util.ts
apps/codebility/app/applicant/waiting/loading.tsx
apps/codebility/app/applicant/waiting/page.tsx
apps/codebility/app/auth/actions.ts
apps/codebility/app/auth/declined/_service/actions.ts
apps/codebility/middleware.ts

added:
new applicant/waiting route
new table in database: applicant {
id,
codev_id
test_taken,
fork_url,
created_at,
updated_at
}
applicant application steps/workflow components

feat: added new applicant workflow

---

apps/codebility/app/applicant/waiting/_component/applicantStep1.tsx
apps/codebility/app/applicant/waiting/_component/applicantStep2.tsx
apps/codebility/app/applicant/waiting/_component/applicationSteps.tsx
apps/codebility/app/applicant/waiting/_component/testInstruction.tsx
apps/codebility/app/applicant/waiting/_component/testQAInstruction.tsx
apps/codebility/app/applicant/waiting/_service/action.ts

changes:
-test automatically taken when user click read instruction
-new test instruction dialog for ui/ux role
-priority roles ["QA Engineer", "Project Manager", "Admin", "Marketing"] skips testing and automatically be on onboarding

Ian/applicant UI/ux test

---

apps/codebility/app/home/_components/LeftSidebar.tsx

fix: active nav link in sidebar now supports nested paths

---

apps/codebility/app/(marketing)/_components/landing/LandingAdminCard.tsx
apps/codebility/app/(marketing)/_components/landing/LandingAdmins.tsx

fix: missing positions for admins and mentors, fix randomColorGenerator

---

apps/codebility/app/home/settings/profile/_components/TimeSchedule.tsx

fix: edit icon for My Time Schedule

---

apps/codebility/app/home/kanban/[projectId]/[id]/_components/KanbanBoard.tsx
apps/codebility/app/home/kanban/[projectId]/[id]/_components/kanban_modals/KanbanAddMembersButton.tsx
apps/codebility/app/home/kanban/[projectId]/[id]/_components/kanban_modals/KanbanAddMembersModal.tsx
apps/codebility/app/home/kanban/[projectId]/[id]/_components/kanban_modals/KanbanColumnAddButton.tsx
apps/codebility/app/home/kanban/[projectId]/[id]/page.tsx

fix: add members button position, skeleton overflowing

fix: add members button position

---

apps/codebility/constants/landing_data.ts

 add a "Career" link below "Contact" in the About Us section

---

apps/codebility/Components/modals/PromoteToCodevModal.tsx
apps/codebility/Components/modals/UserInactiveModal.tsx
apps/codebility/app/home/(dashboard)/_components/DashboardTokenPoints.tsx
apps/codebility/app/home/_components/LeftSidebar.tsx
apps/codebility/app/home/_components/MobileNav.tsx
apps/codebility/app/home/_services/actions.ts
apps/codebility/app/home/page.tsx
apps/codebility/constants/sidebar.ts
apps/codebility/types/home/codev.ts

Codev promotion:
Inactive User view:
Inhouse new role filter:

miguel/ inactive user and codev promotion

---

apps/codebility/app/home/feeds/_components/CreatePostForm.tsx
apps/codebility/app/home/feeds/_components/EditPostForm.tsx
apps/codebility/utils/uploadImage.ts

fix uploadImage function changing the profile Image

miguel/fix uploadImage function

---

apps/codebility/Components/modals/PromoteToMentorModal.tsx
apps/codebility/app/home/(dashboard)/_components/DashboardCertificate.tsx
apps/codebility/app/home/(dashboard)/_components/DashboardDownloadCertificate.tsx
apps/codebility/app/home/(dashboard)/_components/DashboardProfile.tsx
apps/codebility/app/home/(dashboard)/_components/DashboardTokenPoints.tsx
apps/codebility/app/home/_services/actions.ts
apps/codebility/store/codev-store.ts
apps/codebility/types/home/codev.ts

Ask codevs if they want to be promoted to mentor:
Certificates changes based on promotions:
Intern cert:
Codev level 1 cert:
Codev level 2 cert: 
Mentor Cert:

Miguel/add level 2 codev, mentor, and certificates

---

apps/codebility/app/home/my-team/AddMembersModal.tsx
apps/codebility/app/home/my-team/MyTeamPage.tsx
apps/codebility/package.json
pnpm-lock.yaml

dropdown still in-progress

---

apps/codebility/app/home/kanban/[projectId]/[id]/_components/KanbanTask.tsx

Avatar Alignment

---

apps/codebility/app/home/admin-dashboard/_components/AdminDashboardTotalCodev.tsx
apps/codebility/app/home/admin-dashboard/page.tsx

miguel / fix admin dashboard inactive and add total codevs

---

apps/codebility/app/home/kanban/[projectId]/[id]/_components/KanbanBoard.tsx

Root cause: Kanban search bar mislayout

style: fix kanban board mobile layout

---

apps/codebility/app/(marketing)/profiles/[id]/page.tsx

style: added work schedules

---

apps/codebility/app/home/applicants/_components/ApplicantClientWrapper.tsx
apps/codebility/app/home/applicants/_components/ApplicantProfileModal.tsx
apps/codebility/app/home/applicants/_components/TestModal.tsx
apps/codebility/app/home/applicants/_components/_table/applicantActionButton.tsx
apps/codebility/app/home/applicants/_components/applicantFetchComp.tsx
apps/tapup/next-env.d.ts

Add Applicant Profile Modal with View Details Functionality

Add Applicant Profile Modal with View Details Functionality

---

apps/codebility/app/home/_components/LeftSidebar.tsx
apps/codebility/app/home/_components/MobileNav.tsx
apps/codebility/constants/sidebar.ts

change inactive sidebar to not rely on inactive role in the db

miguel/ change inactive

---

apps/codebility/app/(marketing)/profiles/_components/CodevCard.tsx
apps/codebility/app/home/(dashboard)/_components/DashboardWeeklyTop.tsx
apps/codebility/app/home/_components/LeftSidebar.tsx
apps/codebility/app/home/_components/Navbar.tsx
apps/codebility/app/home/page.tsx

The display_position text ("Full Stack Developer") should now be much more readable with the lighter color, providing better contrast against the dark card background while maintaining the visual hierarchy.
Improved readability on dark card backgrounds. LIGHT MODE
Streak Indicator: Commented out the hardcoded "🔥 Streak: 7 days" component
Goal Indicator: Commented out the hardcoded "🎯 Goal: 50 points this week" component
Commented Out Notification Bell Component
Before (with notification bell):
[🔔] [🌓] [👤 User Menu] [☰]
After (without notification bell):
[🌓] [👤 User Menu] [☰]
Before (with unimplemented features):
MENU:
├── 🏠 Home
├── 📊 Kanban
└── 📋 Feeds ❌ (not implemented)
CODEVS:
├── 👥 Codevs
├── 👨‍💼 My Team
├── 🔄 Codev Overflow ❌ (not implemented)
└── 📈 Org Chart
After (filtered …

Improved readability on dark card backgrounds."Full Stack Developer"
